---
version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    ports:
      -"5432:5432"

  web:
    build:: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      DATABASE_URL: >
        postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      -db

  volumes:
    postgres_data:
