---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Reset Docker builder
        run: docker builder prune --force

      - name: Build Docker image
        run: docker build -t flask_auth_path .

      - name: Run container and test
        run: |          
          docker run -d -p 5000:5000 --name test-app \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e SQLALCHEMY_DATABASE_URI=${{ secrets.SQLALCHEMY_DATABASE_URI }} \
            flask_auth_path

      - name: Show container status
        run: docker ps -a

      - name: Test app endpoint
        continue-on-error: true

        run: |
          sleep 15 #Wait for the app to start
          curl -f http://localhost:5000/

      - name: Show container logs
        run: docker logs test-app

      - name: Inspect container
        run: docker inspect test-app
